version: "3.7"

services:
  api:
    restart: on-failure
    image: python:3.7
    working_dir: /var/sources/
    volumes:
      - ../.:/var/sources
    environment:
      - ENV=DEV
      - MODELS_PATH=/var/sources/src/monitoring/models
      - DATA_PATH=/var/sources/src/monitoring/data
    ports:
      - 8080:8080
    command: bash -c "pip install -r requirements.txt && pip install -e . && gunicorn --config gunicorn.conf.py 'app.api:instance_api()'"
